### ISSUE TITLE
[Question] - Import json

### ISSUE THREAD

**Issue by lukasa1993** [al1abb/invoify#546]
how i import exported json?

**Comment by al1abb** [comment]
Once you fill in your invoice form, head over to Export Invoice section on Actions tab.
There you will see an option called 'Export as JSON'

![image](https://github.com/user-attachments/assets/ec86e88d-890f-47d4-b155-d75218813807)

**Comment by lukasa1993** [comment]
> Once you fill in your invoice form, head over to Export Invoice section on Actions tab. There you will see an option called 'Export as JSON'
> 
> ![image](https://private-user-images.githubusercontent.com/60220042/394113535-ec86e88d-890f-47d4-b155-d75218813807.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MDc1MzgsIm5iZiI6MTczMzgwNzIzOCwicGF0aCI6Ii82MDIyMDA0Mi8zOTQxMTM1MzUtZWM4NmU4OGQtODkwZi00N2Q0LWIxNTUtZDc1MjE4ODEzODA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA1MDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MjRkM2MyMDRiOTllYzZmMDE2OWQwNTkxNDdhOGIyOGFhZDBmZjRjYWQ3OWJmNjU1YTA2NGY5NjhkMzZkNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Cj1D1B5m9gY5Qn9FZDTghoAHMpj9dZ6fYXkzPUucBvY)

yes i have exported json, now i want to create new invoice with old data like requring invocie so how i import it back ?

**Comment by al1abb** [comment]
This feature does not exist yet

**Comment by lukasa1993** [comment]
> This feature does not exist yet

hope it will be soon 🤞

**Comment by al1abb** [comment]
This feature has been completed in this PR #563 by @Fuciuss
